Description: "Microservice API and Auth settings"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  PoolName:
    Type: String
  Version:
    Type: String
    Default: v1

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      UserPoolName: !Ref PoolName
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true
  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH

  # You don't actually need the API, but it does allow you to centralize your auth config, and allows you to add an Open API Spec
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServiceApi
      StageName: !Ref Version
      # This is only needed if you are Requesting from a domain that is not shared with this API Domain
      # Know the security implications before doing this on a production site
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"

  StartServer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Start an EC2 instance
      Runtime: go1.x
      Handler: ./dist/start
      Policies:
        - AmazonEC2FullAccess 
      Events:
        Get:
          Type: Api
          Properties:
            Path: /start
            RestApiId: !Ref ServiceApi
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
  StopServer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Stop an EC2 instance
      Runtime: go1.x
      Handler: ./dist/stop
      Policies:
        - AmazonEC2FullAccess 
      Events:
        Get:
          Type: Api
          Properties:
            Path: /stop
            RestApiId: !Ref ServiceApi
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
  StatusServer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get status of an EC2 instance
      Runtime: go1.x
      Handler: ./dist/status
      Policies:
        - AmazonEC2FullAccess 
      Events:
        Get:
          Type: Api
          Properties:
            Path: /status
            RestApiId: !Ref ServiceApi
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  Ping:
    Type: AWS::Serverless::Function
    Properties:
      Description: ping the API
      Runtime: go1.x
      Handler: ./dist/ping
      Events:
        Get:
          Type: Api
          Properties:
            Path: /ping
            RestApiId: !Ref ServiceApi
            Method: GET
Outputs:
  CognitoID:
    Description: The Cognito UserPool ID
    Value: !Ref UserPool
  CognitoClientID:
    Description: The Cognito UserPool Client ID
    Value: !Ref UserPoolTokenClient
  ApiUrl:
    Description: The API URL
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${Version}"
